# Generated by Django 4.2 on 2025-07-26 21:21

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AttendanceLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('in', '出勤'), ('out', '退勤')], max_length=3)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now, verbose_name='サーバタイムスタンプ')),
                ('original_ts', models.DateTimeField(default=django.utils.timezone.now, verbose_name='端末タイムスタンプ (JST)')),
            ],
            options={
                'ordering': ('-timestamp',),
            },
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='氏名')),
                ('wage_type', models.CharField(choices=[('hourly', '時給'), ('salary', '固定給')], default='hourly', max_length=6, verbose_name='賃金種別')),
                ('hourly_rate', models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1)], verbose_name='時給')),
                ('monthly_salary', models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1)], verbose_name='固定給')),
                ('commute_allowance', models.PositiveIntegerField(default=0, verbose_name='通勤手当')),
                ('health_insurance', models.PositiveIntegerField(default=0, verbose_name='健康保険')),
                ('pension', models.PositiveIntegerField(default=0, verbose_name='厚生年金')),
                ('resident_tax', models.PositiveIntegerField(default=0, verbose_name='住民税')),
                ('withholding_tax', models.PositiveIntegerField(default=0, verbose_name='源泉所得税')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='StaffProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qr_token', models.CharField(db_index=True, editable=False, max_length=32, unique=True)),
                ('qr_image', models.ImageField(blank=True, null=True, upload_to='staff_qr')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('staff', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to='attendance_app.staff')),
            ],
        ),
        migrations.CreateModel(
            name='CancelLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('canceled_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('canceled_log', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attendance_app.attendancelog')),
                ('staff', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cancel_logs', to='attendance_app.staff')),
            ],
        ),
        migrations.AddField(
            model_name='attendancelog',
            name='staff',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='attendance_app.staff'),
        ),
    ]
