# Generated by Django 4.2 on 2025-10-19 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='is_retired',
            field=models.BooleanField(default=False, verbose_name='退職済み'),
        ),
        migrations.AddField(
            model_name='staff',
            name='retired_date',
            field=models.DateField(blank=True, null=True, verbose_name='退職日'),
        ),
    ]
