# Generated by Django 4.2 on 2025-10-26 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance_app', '0002_staff_is_retired_staff_retired_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendancelog',
            name='idempotency_key',
            field=models.CharField(blank=True, db_index=True, help_text='重複防止用のIdempotencyキー', max_length=64, null=True),
        ),
    ]
