# Generated by Django 4.2 on 2025-05-18 05:29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PayrollSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('closing_day', models.PositiveSmallIntegerField(default=25, help_text='月次締め日 (1–31)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(31)])),
                ('special_rate', models.DecimalField(decimal_places=2, default=1.35, help_text='休日・特別期間の時給倍率', max_digits=4)),
                ('new_year_from', models.DateField(blank=True, null=True)),
                ('new_year_to', models.DateField(blank=True, null=True)),
                ('bon_from', models.DateField(blank=True, null=True)),
                ('bon_to', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SpecialPeriod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('date_from', models.DateField()),
                ('date_to', models.DateField()),
                ('rate', models.DecimalField(decimal_places=2, default=1.35, max_digits=4)),
            ],
        ),
    ]
