# Generated by Django 4.2 on 2025-05-19 05:17

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='payrollsetting',
            name='weekly_holidays',
            field=models.JSONField(blank=True, default=list, help_text='0=月, …, 6=日 の番号で複数選択可'),
        ),
        migrations.AlterField(
            model_name='payrollsetting',
            name='closing_day',
            field=models.PositiveSmallIntegerField(default=25, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(31)]),
        ),
        migrations.AlterField(
            model_name='payrollsetting',
            name='special_rate',
            field=models.DecimalField(decimal_places=2, default=1.35, max_digits=4),
        ),
    ]
