# Generated by Django 4.2 on 2025-05-19 05:23

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0002_payrollsetting_weekly_holidays_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payrollsetting',
            name='closing_day',
            field=models.PositiveSmallIntegerField(default=25, help_text='月次締め日 (1–31)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(31)]),
        ),
        migrations.AlterField(
            model_name='payrollsetting',
            name='special_rate',
            field=models.DecimalField(decimal_places=2, default=1.35, help_text='休日・特別期間の時給倍率', max_digits=4),
        ),
    ]
