# Generated by Django 4.2 on 2025-05-22 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0003_alter_payrollsetting_closing_day_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='氏名')),
                ('monthly_salary', models.DecimalField(decimal_places=0, max_digits=9, verbose_name='月額固定給')),
                ('deduct_method', models.CharField(choices=[('calendar', '暦日割 (A)'), ('fixed30', '30日割 (B)'), ('working', '所定日割 (C)'), ('work_hour', '所定時間割 (D)'), ('hour_avg', '173.8h割 (E)'), ('weekly', '4.33週割 (F)'), ('nowork', 'ノーワーク=ノーペイ (G)'), ('no_deduct', '控除なし (H)')], default='calendar', max_length=12, verbose_name='日割控除方式')),
            ],
        ),
    ]
