# Generated by Django 4.2 on 2025-05-22 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0004_staff'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='hourly_rate',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True, verbose_name='時給'),
        ),
        migrations.AddField(
            model_name='staff',
            name='wage_type',
            field=models.CharField(choices=[('hourly', '時給'), ('salary', '固定給')], default='hourly', max_length=6, verbose_name='賃金種別'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='deduct_method',
            field=models.CharField(blank=True, choices=[('calendar', '暦日割 (A)'), ('fixed30', '30日割 (B)'), ('working', '所定日割 (C)'), ('work_hour', '所定時間割 (D)'), ('hour_avg', '173.8h割 (E)'), ('weekly', '4.33週割 (F)'), ('nowork', 'ノーワーク=ノーペイ (G)'), ('no_deduct', '控除なし (H)')], default='calendar', max_length=12, null=True, verbose_name='控除方式 (A–H)'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='monthly_salary',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=9, null=True, verbose_name='月額固定給'),
        ),
    ]
