# Generated by Django 4.2 on 2025-05-27 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0006_staff_commute_allowance_staff_employment_ins_rate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='deduct_method',
            field=models.CharField(choices=[('calendar', '暦日割 (A)'), ('fixed30', '30 日固定割 (B)'), ('working', '所定労働日割 (C)'), ('working_hour', '所定労働時間割 (D)'), ('hourly_avg', '173.8 時間割 (E)'), ('weekly', '4.33 週割 (F)'), ('nowork', '欠勤控除 (G)'), ('no_deduct', '控除なし (H)')], default='calendar', max_length=12, verbose_name='控除方式 (A–H)'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='hourly_rate',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True, verbose_name='時給'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='monthly_salary',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=9, null=True, verbose_name='月額固定給'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='name',
            field=models.CharField(max_length=50, verbose_name='氏名'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='wage_type',
            field=models.CharField(choices=[('hourly', '時給'), ('salary', '固定給')], default='hourly', max_length=6, verbose_name='賃金種別'),
        ),
    ]
