# Generated by Django 4.2 on 2025-05-29 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0007_alter_staff_deduct_method_alter_staff_hourly_rate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='withholding_tax',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='staff',
            name='employment_ins_rate',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=8, null=True),
        ),
    ]
