# Generated by Django 4.2 on 2025-06-01 05:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0008_staff_withholding_tax_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staff',
            name='employment_ins_rate',
        ),
    ]
