# Generated by Django 4.2 on 2025-06-02 04:43

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0009_remove_staff_employment_ins_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='payrollsetting',
            name='employment_ins_rate',
            field=models.DecimalField(decimal_places=6, default=Decimal('0.006'), help_text='例 0.006 = 0.6%', max_digits=7, verbose_name='雇用保険率 (%)'),
        ),
    ]
