# Generated by Django 4.2 on 2025-06-04 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0010_payrollsetting_employment_ins_rate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='hourly_rate',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True, verbose_name='時給（￥）'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='monthly_salary',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=9, null=True, verbose_name='月額固定給（￥）'),
        ),
    ]
