# Generated by Django 4.2 on 2025-06-05 07:39

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('payroll', '0011_alter_staff_hourly_rate_alter_staff_monthly_salary'),
    ]

    operations = [
        migrations.CreateModel(
            name='StaffProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('wage_type', models.CharField(choices=[('hourly', '時給'), ('salary', '固定給')], default='hourly', max_length=6)),
                ('hourly_rate', models.PositiveIntegerField(default=0)),
                ('monthly_salary', models.PositiveIntegerField(default=0)),
                ('employment_insured', models.BooleanField(default=True, verbose_name='雇用保険加入')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='staff_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterModelOptions(
            name='specialperiod',
            options={'ordering': ('start',), 'verbose_name': '特別期間', 'verbose_name_plural': '特別期間'},
        ),
        migrations.RenameField(
            model_name='specialperiod',
            old_name='date_from',
            new_name='end',
        ),
        migrations.RenameField(
            model_name='specialperiod',
            old_name='date_to',
            new_name='start',
        ),
        migrations.RemoveField(
            model_name='specialperiod',
            name='name',
        ),
        migrations.RemoveField(
            model_name='specialperiod',
            name='rate',
        ),
        migrations.AddField(
            model_name='specialperiod',
            name='label',
            field=models.CharField(choices=[('new_year', '正月'), ('obon', '盆')], default='new_year', max_length=20),
        ),
        migrations.AddField(
            model_name='specialperiod',
            name='multiplier',
            field=models.DecimalField(decimal_places=2, default=1.25, max_digits=4),
        ),
        migrations.CreateModel(
            name='WorkLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clock_in', models.DateTimeField()),
                ('clock_out', models.DateTimeField(blank=True, null=True)),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payroll.staffprofile')),
            ],
            options={
                'ordering': ('clock_in',),
            },
        ),
        migrations.CreateModel(
            name='MonthlyPayroll',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year_month', models.CharField(max_length=6)),
                ('total_hours', models.DurationField(default=datetime.timedelta)),
                ('special_hours', models.DurationField(default=datetime.timedelta)),
                ('holiday_hours', models.DurationField(default=datetime.timedelta)),
                ('gross_pay', models.PositiveIntegerField(default=0)),
                ('employment_insurance', models.PositiveIntegerField(default=0)),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payroll.staffprofile')),
            ],
            options={
                'ordering': ('year_month', 'staff__id'),
                'unique_together': {('staff', 'year_month')},
            },
        ),
    ]
