# Generated by Django 4.2 on 2025-06-06 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0012_staffprofile_alter_specialperiod_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffprofile',
            name='commute_allowance',
            field=models.PositiveIntegerField(default=0, verbose_name='通勤手当（¥）'),
        ),
        migrations.AddField(
            model_name='staffprofile',
            name='health_insurance',
            field=models.PositiveIntegerField(default=0, verbose_name='健康保険料（¥）'),
        ),
        migrations.AddField(
            model_name='staffprofile',
            name='pension',
            field=models.PositiveIntegerField(default=0, verbose_name='厚生年金（¥）'),
        ),
        migrations.AddField(
            model_name='staffprofile',
            name='resident_tax',
            field=models.PositiveIntegerField(default=0, verbose_name='住民税（¥）'),
        ),
        migrations.AddField(
            model_name='staffprofile',
            name='withholding_tax',
            field=models.PositiveIntegerField(default=0, verbose_name='源泉所得税（¥）'),
        ),
        migrations.AlterField(
            model_name='staffprofile',
            name='employment_insured',
            field=models.BooleanField(default=False, verbose_name='雇用保険加入'),
        ),
    ]
