# Generated by Django 4.2 on 2025-06-07 05:22

from django.db import migrations, models
from datetime import date

def forwards(apps, schema_editor):
    SpecialPeriod = apps.get_model("payroll", "SpecialPeriod")

    # 例：期間名ごとに固定値を入れる
    default_map = {
        "正月": (date(2025, 1, 1), date(2025, 1, 3)),
        "盆":   (date(2025, 8, 13), date(2025, 8, 15)),
    }

    for sp in SpecialPeriod.objects.all():
        if sp.date_from is None or sp.date_to is None:
            df, dt = default_map.get(sp.name, (date(2025, 1, 1), date(2025, 1, 1)))
            sp.date_from = df
            sp.date_to   = dt
            sp.save(update_fields=["date_from", "date_to"])

class Migration(migrations.Migration):

    dependencies = [
        ("payroll", "0013_staffprofile_commute_allowance_and_more"),  # ← 手順2で出来た番号に合わせる
    ]

    operations = [
        migrations.RunPython(forwards, migrations.RunPython.noop),
    ]