# Generated by Django 4.2 on 2025-06-07 07:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0014_populate_specialperiod_dates'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='specialperiod',
            options={},
        ),
        migrations.AddField(
            model_name='specialperiod',
            name='date_from',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='specialperiod',
            name='date_to',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='specialperiod',
            name='name',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='specialperiod',
            name='rate',
            field=models.DecimalField(decimal_places=2, default=1.35, max_digits=4),
        ),
        migrations.AddField(
            model_name='staffprofile',
            name='staff',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='profile', to='payroll.staff'),
        ),
    ]
