# Generated by Django 4.2 on 2025-06-07 07:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0015_alter_specialperiod_options_specialperiod_date_from_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payrollsetting',
            name='bon_from',
            field=models.DateField(default='2025-08-15'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='payrollsetting',
            name='new_year_to',
            field=models.DateField(default='2025-01-04'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='staffprofile',
            name='staff',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to='payroll.staff'),
        ),
    ]
