# Generated by Django 4.2 on 2025-06-07 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0016_alter_payrollsetting_bon_from_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payrollsetting',
            name='bon_from',
            field=models.DateField(blank=True, null=True),
        ),
    ]
