# Generated by Django 4.2 on 2025-06-07 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0017_staffprofile_staff_not_null'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payrollsetting',
            name='bon_from',
            field=models.DateField(),
        ),
    ]
