# Generated by Django 4.2 on 2025-06-07 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0018_staffprofile_staff_set_not_null'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staffprofile',
            name='hourly_rate',
            field=models.PositiveIntegerField(default=0, verbose_name='時給'),
        ),
        migrations.AlterField(
            model_name='staffprofile',
            name='monthly_salary',
            field=models.PositiveIntegerField(default=0, verbose_name='固定給'),
        ),
        migrations.AlterField(
            model_name='staffprofile',
            name='name',
            field=models.CharField(max_length=50, verbose_name='氏名'),
        ),
        migrations.AlterField(
            model_name='staffprofile',
            name='wage_type',
            field=models.CharField(choices=[('hourly', '時給'), ('salary', '固定給')], default='hourly', max_length=6, verbose_name='時給/固定給'),
        ),
    ]
