# Generated by Django 4.2 on 2025-06-08 05:11

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0019_alter_staffprofile_hourly_rate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffprofile',
            name='qr_image',
            field=models.ImageField(blank=True, null=True, upload_to='qr/'),
        ),
        migrations.AddField(
            model_name='staffprofile',
            name='qr_token',
            field=models.CharField(blank=True, default=uuid.uuid4, editable=False, max_length=64, null=True),
        ),
    ]
