# Generated by Django 4.2 on 2025-06-08 05:19

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0020_staffprofile_qr_image_staffprofile_qr_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staffprofile',
            name='qr_token',
            field=models.CharField(default=uuid.uuid4, editable=False, max_length=64, unique=True),
        ),
    ]
