# Generated by Django 4.2 on 2025-06-13 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0022_staffprofile_qr_unique'),
    ]

    operations = [
        migrations.AddField(
            model_name='monthlypayroll',
            name='health_insurance',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='monthlypayroll',
            name='pension',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='monthlypayroll',
            name='resident_tax',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='monthlypayroll',
            name='withholding_tax',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
