# Generated by Django 4.2 on 2025-06-15 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0025_sync_staffprofile_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='monthlypayroll',
            name='commute_allowance',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
