# Generated by Django 4.2 on 2025-06-15 23:01

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0026_monthlypayroll_commute_allowance'),
    ]

    operations = [
    ]
