# Generated by Django 4.2 on 2025-06-15 23:07
from django.db import migrations

def set_names(apps, schema_editor):
    SpecialPeriod = apps.get_model('payroll', 'SpecialPeriod')
    for sp in SpecialPeriod.objects.filter(name__isnull=True):
        # 適当にラベル → name へコピー、または固定文字を入れるなど
        sp.name = sp.get_label_display()  # 例
        sp.save(update_fields=['name'])

class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0027_specialperiod_name_nullable'),  # 直前のスキーマ migration
    ]

    operations = [
        migrations.RunPython(set_names, migrations.RunPython.noop),
    ]