# Generated by Django 4.2 on 2025-06-15 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0028_populate_specialperiod_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='specialperiod',
            name='name',
            field=models.CharField(default='未設定', max_length=30),
        ),
    ]
