# Generated by Django 4.2 on 2025-07-26 21:21

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0029_specialperiod_name_not_null'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='monthlypayroll',
            options={'ordering': ('year_month', 'staff_id')},
        ),
        migrations.RemoveField(
            model_name='specialperiod',
            name='date_from',
        ),
        migrations.RemoveField(
            model_name='specialperiod',
            name='date_to',
        ),
        migrations.RemoveField(
            model_name='specialperiod',
            name='label',
        ),
        migrations.RemoveField(
            model_name='specialperiod',
            name='rate',
        ),
        migrations.RemoveField(
            model_name='staffprofile',
            name='commute_allowance',
        ),
        migrations.RemoveField(
            model_name='staffprofile',
            name='employment_insured',
        ),
        migrations.RemoveField(
            model_name='staffprofile',
            name='health_insurance',
        ),
        migrations.RemoveField(
            model_name='staffprofile',
            name='hourly_rate',
        ),
        migrations.RemoveField(
            model_name='staffprofile',
            name='monthly_salary',
        ),
        migrations.RemoveField(
            model_name='staffprofile',
            name='name',
        ),
        migrations.RemoveField(
            model_name='staffprofile',
            name='pension',
        ),
        migrations.RemoveField(
            model_name='staffprofile',
            name='resident_tax',
        ),
        migrations.RemoveField(
            model_name='staffprofile',
            name='wage_type',
        ),
        migrations.RemoveField(
            model_name='staffprofile',
            name='withholding_tax',
        ),
        migrations.AlterField(
            model_name='payrollsetting',
            name='bon_from',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='payrollsetting',
            name='employment_ins_rate',
            field=models.DecimalField(decimal_places=6, default=Decimal('0.006'), help_text='例 0.006 = 0.6%', max_digits=7, verbose_name='雇用保険率'),
        ),
        migrations.AlterField(
            model_name='payrollsetting',
            name='new_year_to',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='payrollsetting',
            name='weekly_holidays',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='specialperiod',
            name='multiplier',
            field=models.DecimalField(decimal_places=2, default=1.35, max_digits=4),
        ),
        migrations.AlterField(
            model_name='staff',
            name='commute_allowance',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=7, null=True, verbose_name='通勤手当(¥)'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='health_insurance',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=8, null=True, verbose_name='健康保険料(¥)'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='pension',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=8, null=True, verbose_name='厚生年金(¥)'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='resident_tax',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=8, null=True, verbose_name='住民税(¥)'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='withholding_tax',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=8, null=True, verbose_name='源泉所得税(¥)'),
        ),
    ]
