# Generated by Django 4.2 on 2025-08-07 05:26

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0030_alter_monthlypayroll_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='staff',
            options={'ordering': ('name',)},
        ),
        migrations.AlterField(
            model_name='monthlypayroll',
            name='year_month',
            field=models.CharField(max_length=6, validators=[django.core.validators.RegexValidator('^\\d{6}$')]),
        ),
        migrations.AlterField(
            model_name='payrollsetting',
            name='bon_from',
            field=models.DateField(blank=True, null=True, verbose_name='盆From'),
        ),
        migrations.AlterField(
            model_name='payrollsetting',
            name='bon_to',
            field=models.DateField(blank=True, null=True, verbose_name='盆To'),
        ),
        migrations.AlterField(
            model_name='payrollsetting',
            name='closing_day',
            field=models.PositiveSmallIntegerField(default=25, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(31)], verbose_name='締め日'),
        ),
        migrations.AlterField(
            model_name='payrollsetting',
            name='employment_ins_rate',
            field=models.DecimalField(decimal_places=6, default=Decimal('0.006'), max_digits=7, verbose_name='雇用保険率'),
        ),
        migrations.AlterField(
            model_name='payrollsetting',
            name='new_year_from',
            field=models.DateField(blank=True, null=True, verbose_name='正月From'),
        ),
        migrations.AlterField(
            model_name='payrollsetting',
            name='new_year_to',
            field=models.DateField(blank=True, null=True, verbose_name='正月To'),
        ),
        migrations.AlterField(
            model_name='payrollsetting',
            name='special_rate',
            field=models.DecimalField(decimal_places=2, default=1.35, max_digits=4, verbose_name='特別日倍率'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='commute_allowance',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=7, null=True, verbose_name='通勤手当'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='health_insurance',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=8, null=True, verbose_name='健康保険'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='hourly_rate',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True, verbose_name='時給'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='pension',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=8, null=True, verbose_name='厚生年金'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='resident_tax',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=8, null=True, verbose_name='住民税'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='withholding_tax',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=8, null=True, verbose_name='源泉所得税'),
        ),
        migrations.AddIndex(
            model_name='monthlypayroll',
            index=models.Index(fields=['staff', 'year_month'], name='payroll_mon_staff_i_e221d1_idx'),
        ),
    ]
