# Generated by Django 4.2 on 2025-08-08 05:46

from decimal import Decimal
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('attendance_app', '0001_initial'),
        ('payroll', '0031_alter_staff_options_alter_monthlypayroll_year_month_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PayrollInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deduct_method', models.CharField(choices=[('calendar', '暦日割 (A)'), ('fixed30', '30 日固定割 (B)'), ('working', '所定労働日割 (C)'), ('working_hour', '所定労働時間割 (D)'), ('hourly_avg', '173.8 時間割 (E)'), ('weekly', '4.33 週割 (F)'), ('nowork', '欠勤控除 (G)'), ('no_deduct', '控除なし (H)')], default='calendar', max_length=12, verbose_name='控除方式')),
                ('employment_insured', models.BooleanField(default=False, verbose_name='雇用保険加入')),
                ('resident_tax', models.DecimalField(blank=True, decimal_places=0, max_digits=8, null=True, verbose_name='住民税(¥)')),
                ('withholding_tax', models.DecimalField(blank=True, decimal_places=0, max_digits=8, null=True, verbose_name='源泉所得税(¥)')),
                ('health_insurance', models.DecimalField(blank=True, decimal_places=0, max_digits=8, null=True, verbose_name='健康保険料(¥)')),
                ('pension', models.DecimalField(blank=True, decimal_places=0, max_digits=8, null=True, verbose_name='厚生年金(¥)')),
                ('commute_allowance', models.DecimalField(blank=True, decimal_places=0, max_digits=7, null=True, verbose_name='通勤手当(¥)')),
            ],
            options={
                'verbose_name': 'Payroll Info',
                'verbose_name_plural': 'Payroll Infos',
            },
        ),
        migrations.RemoveField(
            model_name='staffprofile',
            name='staff',
        ),
        migrations.RemoveField(
            model_name='staffprofile',
            name='user',
        ),
        migrations.AlterField(
            model_name='monthlypayroll',
            name='staff',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attendance_app.staff'),
        ),
        migrations.AlterField(
            model_name='payrollsetting',
            name='bon_from',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='payrollsetting',
            name='bon_to',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='payrollsetting',
            name='closing_day',
            field=models.PositiveSmallIntegerField(default=25, help_text='月次締め日 (1–31)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(31)]),
        ),
        migrations.AlterField(
            model_name='payrollsetting',
            name='employment_ins_rate',
            field=models.DecimalField(decimal_places=6, default=Decimal('0.006'), help_text='例 0.006 = 0.6%', max_digits=7, verbose_name='雇用保険率'),
        ),
        migrations.AlterField(
            model_name='payrollsetting',
            name='new_year_from',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='payrollsetting',
            name='new_year_to',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='payrollsetting',
            name='special_rate',
            field=models.DecimalField(decimal_places=2, default=1.35, help_text='休日・特別期間の時給倍率', max_digits=4),
        ),
        migrations.DeleteModel(
            name='Staff',
        ),
        migrations.DeleteModel(
            name='StaffProfile',
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
            ],
            options={
                'verbose_name': 'Staff',
                'verbose_name_plural': 'Staffs',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('attendance_app.staff',),
        ),
        migrations.CreateModel(
            name='StaffProfile',
            fields=[
            ],
            options={
                'verbose_name': 'Staff profile',
                'verbose_name_plural': 'Staff profiles',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('attendance_app.staffprofile',),
        ),
        migrations.AddField(
            model_name='payrollinfo',
            name='staff',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payroll_info', to='payroll.staff'),
        ),
    ]
