# Generated by Django 4.2 on 2025-09-27 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0032_payrollinfo_remove_staffprofile_staff_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payrollinfo',
            name='deduct_method',
            field=models.CharField(blank=True, choices=[('calendar', '暦日割 (A)'), ('fixed30', '30 日固定割 (B)'), ('working', '所定労働日割 (C)'), ('working_hour', '所定労働時間割 (D)'), ('hourly_avg', '173.8 時間割 (E)'), ('weekly', '4.33 週割 (F)'), ('nowork', '欠勤控除 (G)'), ('no_deduct', '控除なし (H)')], default='no_deduct', max_length=12, null=True, verbose_name='控除方式'),
        ),
    ]
