# Generated by Django 4.2 on 2025-10-02 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0033_alter_payrollinfo_deduct_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='payrollsetting',
            name='gw_from',
            field=models.DateField(blank=True, null=True, verbose_name='GW開始日'),
        ),
        migrations.AddField(
            model_name='payrollsetting',
            name='gw_to',
            field=models.DateField(blank=True, null=True, verbose_name='GW終了日'),
        ),
        migrations.AlterField(
            model_name='payrollsetting',
            name='bon_from',
            field=models.DateField(blank=True, null=True, verbose_name='盆開始日'),
        ),
        migrations.AlterField(
            model_name='payrollsetting',
            name='bon_to',
            field=models.DateField(blank=True, null=True, verbose_name='盆終了日'),
        ),
        migrations.AlterField(
            model_name='payrollsetting',
            name='new_year_from',
            field=models.DateField(blank=True, null=True, verbose_name='正月開始日'),
        ),
        migrations.AlterField(
            model_name='payrollsetting',
            name='new_year_to',
            field=models.DateField(blank=True, null=True, verbose_name='正月終了日'),
        ),
    ]
