# Generated by Django 4.2 on 2025-10-20 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0034_payrollsetting_gw_from_payrollsetting_gw_to_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payrollsetting',
            name='worktime_rule',
            field=models.CharField(choices=[('rounded', '丸め処理あり'), ('raw', '実働そのまま')], default='rounded', help_text='勤務時間集計時のルールを選択してください。', max_length=16, verbose_name='勤務時間の集計ルール'),
        ),
    ]
