# Generated by Django 4.2 on 2025-10-19 04:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0034_payrollsetting_gw_from_payrollsetting_gw_to_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payrollsetting',
            name='lunch_break_from',
            field=models.TimeField(default=datetime.time(12, 0), verbose_name='昼休憩開始時刻'),
        ),
        migrations.AddField(
            model_name='payrollsetting',
            name='lunch_break_to',
            field=models.TimeField(default=datetime.time(13, 0), verbose_name='昼休憩終了時刻'),
        ),
    ]
