# Generated by Django 4.2 on 2025-10-26 20:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0035_payrollsetting_lunch_break_from_and_more'),
        ('payroll', '0035_payrollsetting_worktime_rule'),
    ]

    operations = [
    ]
