# Generated by Django 4.2 on 2025-10-27 20:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0036_merge_20251027_0546'),
    ]

    operations = [
        migrations.AddField(
            model_name='monthlypayroll',
            name='normal_hours',
            field=models.DurationField(default=datetime.timedelta),
        ),
    ]
